version: "3.8"

services:
  postgres:
    image: postgres:15  # Use a specific version of PostgreSQL
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: weatherdb
    ports:
      - "127.0.0.1:5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:  # Named volume for data persistence
