version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    restart: always
    env_file: 
      - .env
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  pgdata:
